@accessToken = {{login.response.body.$.access_token}}
@backendHost = http://localhost:3000
@loginHost = http://localhost:8080

###
# @name login
POST {{loginHost}}/auth/realms/fincycle/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=nest
&client_secret=96117742-b488-4860-a84a-63d53df33607
&grant_type=password
&username=user1@user.com
&password=123456

###
# @name failCreateAccount
POST {{backendHost}}/accounts
Content-Type: application/json

{}

###
# @name createAccount
POST {{backendHost}}/accounts
Content-Type: application/json

{
    "name": "Account 1",
    "subdomain": "tenant1"
}

###
# @name retrieveAccounts
GET {{backendHost}}/accounts

###
# @name unauthorizeCreateTransaction
POST {{backendHost}}/transactions
Content-Type: application/json

{}

###
# @name failCreateTransaction
POST {{backendHost}}/transactions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{}

###
# @name createTransaction
POST {{backendHost}}/transactions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "payment_date": "2021-01-01",
  "name": "Nova conta 1",
  "description": "Descrição",
  "category": "category1",
  "amount": 30,
  "type": "debit"
}

###
# @name retrieveTransactions
GET {{backendHost}}/transactions
Authorization: Bearer {{accessToken}}

###
# @name generateReport
GET {{backendHost}}/reports
Authorization: Bearer {{accessToken}}

###
# @name generateReport-with-period
POST {{backendHost}}/reports
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "start_date": "2021-01-01",
  "end_date": "2021-01-02"
}
