version: "3"

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host-local.docker.internal:172.17.0.1"
# Add host config in hosts file
#
# /etc/hosts
# c:\Windows\system32\drivers\etc\hosts
#
# 127.0.0.1 host-local.docker.internal
